
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
   

  apartment-service:
    build:
      context: ./apartment-service
    container_name: apartment-service
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlite:/app/apartments.db
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq
    volumes:
      - ./apartment-service/apartments.db:/app/apartments.db  # ✅ Correct path

  booking-service:
    build:
      context: ./booking-service
    container_name: booking-service
    ports:
      - "8087:8087"
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlite:/app/booking.db
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq
      - apartment-service
    volumes:
      - ./booking-service/booking.db:/app/booking.db  # ✅ Correct path

  search-service:
    build:
      context: ./search-service
    container_name: search-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlite:/app/search.db
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq
    volumes:
      - ./search-service/search.db:/app/search.db  # ✅ Correct path

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - apartment-service
      - booking-service
      - search-service

volumes:
  apartment-data:
  booking-data:
  search-data:
